import copy
import itertools

import numpy as np
import torch
from torch.utils.data.sampler import Sampler

from hat.registry import OBJECT_REGISTRY
from hat.utils.distributed import get_dist_info

__all__ = ["DistributedGroupInBatchSampler"]


@OBJECT_REGISTRY.register
class DistributedGroupInBatchSampler(Sampler):
    """Samples with the same flag are assigned to the same batch index.

    Args:
        dataset: the dataset to sampling
        batch_size: number of samples in a batch
        world_size: number of processes
        rank: the index of current process
        seed: random seed
        skip_prob: Probability of skipping a sample at random
        keep_consistent_group_aug: whether to maintain data augumentaion config
            in a group, the dataset needs to have the get_aug_configs function
        stop_by_epoch: whether to stop iteration at an epoch
        drop_last: whether drop the last incomplete batch, only valid when
            stop_by_epoch=True

    Example:
        Suppose we have a dataset with samples and each sample has a 'flag':
        dataset = [a, b, c, d, e, f]
        dataset.flag = [1, 1, 1, 2, 2, 2]

        We can use the DistributedGroupInBatchSampler to create batches where
        samples with the same flag are grouped in fixed batch index:

        The batches generated by the DistributedGroupInBatchSampler with
        batch_size=2 will be:
        Batch 1: [a, d]
        Batch 2: [b, e]
        Batch 3: [c, f]

    """

    def __init__(
        self,
        dataset,
        batch_size=1,
        world_size=None,
        rank=None,
        seed=0,
        skip_prob=-1.0,
        max_skip_num=10,
        keep_consistent_group_aug=False,
        stop_by_epoch=False,
        drop_last=False,
    ):
        _rank, _world_size = get_dist_info()
        if world_size is None:
            world_size = _world_size
        if rank is None:
            rank = _rank

        self.dataset = dataset
        self.batch_size = batch_size
        self.world_size = world_size
        self.rank = rank
        self.seed = seed
        self.skip_prob = skip_prob
        self.max_skip_num = max_skip_num
        self.keep_consistent_group_aug = keep_consistent_group_aug
        self.stop_by_epoch = stop_by_epoch
        self.drop_last = drop_last

        if keep_consistent_group_aug:
            assert hasattr(self.dataset, "get_aug_configs")
            self.group_aug_configs = [None for _ in range(self.batch_size)]

        self.size = len(self.dataset)

        assert hasattr(self.dataset, "flag")
        self.flag = self.dataset.flag
        self.group_sizes = np.bincount(self.flag)
        self.num_groups = len(self.group_sizes)
        self.global_batch_size = batch_size * world_size
        assert self.num_groups >= self.global_batch_size

        self.group_idx_to_sample_idxs = {
            group_idx: np.where(self.flag == group_idx)[0].tolist()
            for group_idx in range(self.num_groups)
        }
        self._reset()

    def _infinite_group_indices(self):
        g = torch.Generator()
        g.manual_seed(self.seed)
        while True:
            yield from torch.randperm(self.num_groups, generator=g).tolist()

    def _epoch_group_indices(self):
        for idx in range(self.num_groups):
            yield idx

    def _group_indices_queue_generator(self, global_sample_idx):
        yield from itertools.islice(
            self._epoch_group_indices()
            if self.stop_by_epoch
            else self._infinite_group_indices(),
            global_sample_idx,
            None,
            self.global_batch_size,
        )

    def __iter__(self):
        while True:
            curr_batch = []
            for sample_index in range(self.batch_size):
                if len(self.sample_indices_queues[sample_index]) == 0:
                    try:
                        new_group_idx = next(
                            self.group_indices_queues[sample_index]
                        )
                    except StopIteration:
                        if self.drop_last:
                            self._reset()
                            return
                        self.stop_flags[sample_index] = True
                        if sum(self.stop_flags) == len(self.stop_flags):
                            self._reset()
                            return
                        self.group_indices_queues[
                            sample_index
                        ] = self._group_indices_queue_generator(
                            self.rank * self.batch_size + sample_index
                        )

                    self.sample_indices_queues[sample_index] = copy.deepcopy(
                        self.group_idx_to_sample_idxs[new_group_idx]
                    )
                    if self.keep_consistent_group_aug:
                        self.group_aug_configs[
                            sample_index
                        ] = self.dataset.get_aug_configs()

                skip_cnt = 0
                while (
                    np.random.uniform() < self.skip_prob
                    and len(self.sample_indices_queues[sample_index]) > 1
                    and skip_cnt < self.max_skip_num
                ):
                    self.sample_indices_queues[sample_index].pop(0)
                    skip_cnt += 1

                index = self.sample_indices_queues[sample_index].pop(0)
                if not self.keep_consistent_group_aug:
                    curr_batch.append(index)
                else:
                    curr_batch.append(
                        {
                            "index": index,
                            "aug_configs": self.group_aug_configs[
                                sample_index
                            ],
                        }
                    )
            yield curr_batch

    def __len__(self):
        """Length of base dataset."""
        return self.size

    def set_epoch(self, epoch):
        self.epoch = epoch

    def _reset(self):
        self.group_indices_queues = [
            self._group_indices_queue_generator(
                self.rank * self.batch_size + sample_index
            )
            for sample_index in range(self.batch_size)
        ]
        self.sample_indices_queues = [[] for _ in range(self.batch_size)]
        self.stop_flags = [False for _ in range(self.batch_size)]
