import copy

import torch

from projects.cloudmodel.configs.perception_2d.common import (
    backbone,
    batch_size_per_gpu,
    fast_debug_dataset_number,
    num_workers,
    task_inputs,
    transforms,
    use_all_data,
)
from projects.cloudmodel.configs.perception_2d.data import HorizonDataset
from projects.cloudmodel.configs.perception_2d.data import (
    build_singletask_dataloader as build_dataloader,
)
from projects.cloudmodel.configs.perception_2d.metrics import get_metrics
from projects.cloudmodel.configs.perception_2d.models import (
    build_attribute_classifier,
)
from projects.cloudmodel.configs.perception_2d.tasks.all_tasks import AllTasks

# ------------------------------ task setting ------------------------------ #
task = AllTasks.traffic_sign_recognition_classification
task_name = task.task_name

task_loss_weight = 1.0

num_classes = 419  # sum([len(ii) for _,ii in name_dict.items()])
attr_type_list = ["cn_sub_type"]
attr_type_value = [419]
ignore_idx = []
confidence_idx = []
occlusion_idx = []
type_ignore_bad = False  # True #
ignore_idxs = ignore_idx + confidence_idx + occlusion_idx

name_dict = {
    "cn_sub_type": [
        "W_Other",
        "W_Unknown",
        "W_Cross",
        "W_Tshaps",
        "W_TShapRight",
        "W_TShapLeft",
        "W_Tshape",
        "W_YBLeft",
        "W_YBRight",
        "W_YLeft",
        "W_YRight",
        "W_Circle",
        "W_LeftTurn",
        "W_RightTurn",
        "W_LRTurn",
        "W_RLTurn",
        "W_ContinuousTurn",
        "W_Up",
        "W_Down",
        "W_ContinuousDown",
        "W_LeftNarrow",
        "W_RightNarrow",
        "W_LRNarrow",
        "W_NarrowBridge",
        "W_TwoWay",
        "W_Pedestrian",
        "W_Children",
        "W_Domestic",
        "W_Animal",
        "W_TrafficLight",
        "W_LeftFalling",
        "W_RightFalling",
        "W_SideWind",
        "W_Slip",
        "W_MountLeft",
        "W_MountRight",
        "W_DamRight",
        "W_DamLeft",
        "W_Village",
        "W_Tunnel",
        "W_Ferry",
        "W_HumpBridge",
        "W_Bumpy",
        "W_Bump",
        "W_LowLying",
        "W_Ford",
        "W_GuardedRailway",
        "W_Railway",
        "W_Cycle",
        "W_Disabled",
        "W_AccidentProne",
        "W_Slow",
        "W_DetourAround",
        "W_DetourLeft",
        "W_DetourRight",
        "W_Danger",
        "W_Working",
        "W_SlowDown",
        "W_TunnelHeadlight",
        "W_Tidal",
        "W_KeepDistance",
        "W_CrossIntersection",
        "W_TIntersection",
        "W_MergeLeft",
        "W_MergeRight",
        "W_SplitLeft",
        "W_SplitRight",
        "W_EmergencyLane",
        "W_Ice",
        "W_Rain",
        "W_Fog",
        "W_BadWeather",
        "W_VehicleQueue",
        "P_Other1",
        "P_Unknown1",
        "P_StopFor",
        "P_SlowFor",
        "P_GiveWay",
        "P_Noway",
        "P_NoEntry",
        "P_NoMotor",
        "P_NoCar",
        "P_NoTruck",
        "P_NoTricycle",
        "P_NoBus",
        "P_NoMinibus",
        "P_NoTrailer",
        "P_NoTractor",
        "P_NoCargoTricycle",
        "P_NoMotorcycle",
        "P_MultiVehicle",
        "P_NoNonMotor",
        "P_NoAnimalVehicle",
        "P_NoHumanCargoTriangle",
        "P_NoHumanPassengerTriangle",
        "P_NoHumanVehicle",
        "P_VehicleOther",
        "P_NoHuman",
        "P_NoLeftTurn",
        "P_NoSpecificLeftTurn",
        "P_NoRightTurn",
        "P_NoSpecificRightTurn",
        "P_NoForward",
        "P_NoLeftRightTurn",
        "P_NoForwardLeft",
        "P_NoForwardRight",
        "P_NoReturn",
        "P_NoPassing",
        "P_NoParking",
        "P_NoLongParking",
        "P_NoHorning",
        "P_WidthLim",
        "P_HeightLim",
        "P_WeightLim",
        "P_WeightLimWheel",
        "P_NoBikeDownSlope",
        "P_NoBikeUpSlope",
        "P_ParkingCheck",
        "P_NoDangerous",
        "P_Custom",
        "P_Other_SpeedLimele",
        "P_Unknow_SpeedLimele",
        "P_SpeedLim20ele",
        "P_SpeedLim30ele",
        "P_SpeedLim40ele",
        "P_SpeedLim50ele",
        "P_SpeedLim60ele",
        "P_SpeedLim70ele",
        "P_SpeedLim80ele",
        "P_SpeedLim90ele",
        "P_SpeedLim100ele",
        "P_SpeedLim110ele",
        "P_SpeedLim120ele",
        "PSL_Other",
        "PSL_Unknown",
        "P_SpeedLim5",
        "P_SpeedLim10",
        "P_SpeedLim15",
        "P_SpeedLim20",
        "P_SpeedLim25",
        "P_SpeedLim30",
        "P_SpeedLim35",
        "P_SpeedLim40",
        "P_SpeedLim45",
        "P_SpeedLim50",
        "P_SpeedLim55",
        "P_SpeedLim60",
        "P_SpeedLim65",
        "P_SpeedLim70",
        "P_SpeedLim75",
        "P_SpeedLim80",
        "P_SpeedLim85",
        "P_SpeedLim90",
        "P_SpeedLim95",
        "P_SpeedLim100",
        "P_SpeedLim105",
        "P_SpeedLim110",
        "P_SpeedLim115",
        "P_SpeedLim120",
        "PR_Other",
        "PR_Unknown",
        "P_SpeedLimRev5",
        "P_SpeedLimRev10",
        "P_SpeedLimRev15",
        "P_SpeedLimRev20",
        "P_SpeedLimRev25",
        "P_SpeedLimRev30",
        "P_SpeedLimRev35",
        "P_SpeedLimRev40",
        "P_SpeedLimRev45",
        "P_SpeedLimRev50",
        "P_SpeedLimRev55",
        "P_SpeedLimRev60",
        "P_SpeedLimRev65",
        "P_SpeedLimRev70",
        "P_SpeedLimRev75",
        "P_SpeedLimRev80",
        "P_SpeedLimRev85",
        "P_SpeedLimRev90",
        "P_SpeedLimRev95",
        "P_SpeedLimRev100",
        "P_SpeedLimRev105",
        "P_SpeedLimRev110",
        "P_SpeedLimRev115",
        "P_SpeedLimRev120",
        "P_NoPassingRev",
        "P_NoLongParkingRev",
        "P_NoParkingRev",
        "MSL_Other",
        "MSL_Unknown",
        "I_MinSpeedLim40",
        "I_MinSpeedLim50",
        "I_MinSpeedLim60",
        "I_MinSpeedLim70",
        "I_MinSpeedLim80",
        "I_MinSpeedLim90",
        "I_MinSpeedLim100",
        "I_MinSpeedLim110",
        "I_Other_circle",
        "I_Unknown_circle",
        "I_Forward",
        "I_LeftTurn",
        "I_RightTurn",
        "I_Uturn",
        "I_ForwardLeft",
        "I_ForwardRight",
        "I_LeftRight",
        "I_Right",
        "I_Left",
        "I_ForwardLeftStereo",
        "I_ForwardRightStereo",
        "I_Circle",
        "I_Walk",
        "I_Honk",
        "I_Motors",
        "I_NonMotors",
        "I_Other_rectangle",
        "I_Unknown_rectangle",
        "I_RightLine",
        "I_LeftLine",
        "I_StraightLine",
        "I_PriorityIntereesction",
        "I_Passingfirst",
        "I_PedestrianCross",
        "I_RightTurnLane",
        "I_LeftTurnLane",
        "I_ForwardLane",
        "I_ForwardRightLane",
        "I_ForwardLeftLane",
        "I_UTurnLane",
        "I_UTurnAndLeftLane",
        "I_SplitDriveLine",
        "I_LeftBusLane",
        "I_MotorsLane",
        "I_NonMotorsLane",
        "I_FastBusLane",
        "I_MultiOccupantMotorsLane",
        "I_ParkingSpace",
        "I_AllowUturn",
        "GSWB_Other",
        "GSWB_Unknown",
        "IR_PassingTime",
        "IR_VehicleType",
        "IR_DrivingDirection",
        "IR_Area",
        "IR_DistanceArea",
        "IR_WarningReason",
        "IR_CombinationAuxiliary",
        "IR_Ramp",
        "IR_RampArrow",
        "GSWB_Misc",
        "C_Other",
        "C_Unknown",
        "IR_MobileConstruction",
        "IR_CrossingMarking",
        "IR_RoadStop",
        "IR_ZonesII",
        "IR_Zones",
        "R_RoadSign_BlueWhite",
        "RSBW_Other",
        "RSBW_Unknown",
        "IR_IntersectionNotice",
        "IR_CrossIntersection",
        "IR_Tcorssing",
        "IR_Ycorssing",
        "R_CircularIntersection",
        "IR_Interchange",
        "IR_BifurcationMark",
        "IR_StreetName",
        "IR_Nameplate",
        "IR_LocationDistance",
        "IR_PlaceName",
        "IR_FamousPlaceName",
        "IR_AdministrativeBoundary",
        "IR_RoadManageBoundary",
        "IR_PedestrianTunnel",
        "IR_BusStation",
        "IR_LongDistanceBusStation",
        "IR_RailwayStation",
        "IR_SubwayStation",
        "IR_Airport",
        "IR_Port",
        "IR_TransferCenter",
        "IR_FerryPier",
        "IR_Ferry",
        "IR_FirstAidStation",
        "IR_CarRepair",
        "IR_CarWash",
        "IR_Taxi",
        "IR_GasStation",
        "IR_Accommodation",
        "IR_CateringServices",
        "IR_Snack",
        "IR_Drink",
        "IR_Police",
        "IR_Quarantine",
        "IR_ParkingLot",
        "IR_AvoidLine",
        "IR_FootBridge",
        "IR_PedestrianUnderpass",
        "IR_DisabledSpecial",
        "IR_SlowRoad",
        "IR_SteepSlope",
        "IR_Foggy",
        "IR_SoftFoundation",
        "IR_BigCarRight",
        "IR_TransverseWind",
        "IR_AccidentPronePoint",
        "IR_ContinuousDownhill",
        "IR_Tunnel",
        "IR_ProtectAnimals",
        "IR_ViewingPoint",
        "IR_EmergencyShelter",
        "IR_RestArea",
        "IR_Blocked",
        "IR_LanesDecrease",
        "IR_LanesIncrease",
        "IR_TrafficSupervisory",
        "IR_TunnelNextExitNotice",
        "IR_MilePost",
        "RSBW_Misc",
        "G_GuideSign_GreenWhite",
        "GSGW_Other",
        "GSGW_Unknown",
        "IR_HighwayEntranceNotice",
        "IR_HighwayEntrance",
        "IR_HighwayLocationDirection",
        "IR_HighwayName",
        "IR_HighwayLocationDistance",
        "IR_HighwayNextExitNotice",
        "IR_HighwayExitNotice",
        "IR_HighwayExit",
        "IR_HighwayStart",
        "IR_HighwayEndNotice",
        "IR_HighwayEnd",
        "IR_HighwayRoadTrafficInformation",
        "IR_HighwayMileageCard",
        "IR_HighwayTicket",
        "IR_HighwayCarDistanceConfirmation",
        "IR_HighwaySlowDown",
        "IR_HighwayEmergencyPhone",
        "IR_HighwayRescueCall",
        "IR_HighwayTollStationsNotice",
        "IR_HighwayETCLanes",
        "IR_WeightCharge",
        "IR_HighwayGasStation",
        "IR_HighwayEmergencyParkingBelt",
        "IR_HighwayServiceNotice",
        "IR_HighwayParkinAreaNotice",
        "IR_HighwayParkingLotNotice",
        "IR_HighwayClimbingLine",
        "IR_HighwayOverloadCheck",
        "IR_HighwayDirection",
        "GSGW_Misc",
        "T_TravelSign_BrownWhite",
        "TSBW_Other",
        "TSBW_Unknown",
        "IR_TouristAreaDirectionDistance",
        "IR_TravelSymbols",
        "sign_back",
        "O_Other",
        "W_CrossLaneRail",
        "W_Slash",
        "IR_HighwayHundredCard",
        "IR_Parking",
        "IR_Linearguide",
        "IR_HighwayETCTollStationsNotice",
        "IR_ETCLanes",
        "IR_ElectricalETC",
        "GuideSign_MultiMisc",
        "U_Unknown",
        "RouteID_Other",
        "RouteID_Unknown",
        "RouteID_RedWhite",
        "RouteID_YellowBlack",
        "IR_CountryRoadNumMark",
        "RouteID_TownRoadMark",
        "RouteID_HighwayMark",
        "W_Tripod",
        "FP_Route_Number",
        "FP_Mirror",
        "FP_Circular_Marker",
        "FP_Polygon_Marker",
        "FP_Vehicle_Wheel",
        "FP_Light_Shell",
        "FP_Light_Arrow",
        "FP_Light_Circle",
        "FP_Light_Time",
        "FP_Building",
        "FP_Twig",
        "FP_Head",
        "FP_Accessory_Arrow",
        "FP_Other",
        "FP_Unknown",
        "FP_IncompleteSign",
        "FP_SignWithContext",
        "IR_AuxiliaryRoad",
        "IR_RampAhead",
        "IR_RampDirection",
        "IR_RampExit",
        "IR_RampHighwayExit",
        "IR_RampInternal",
        "IR_RampOut",
        "IR_RightLane",
        "IR_SpecificRamp",
        "W_Misc",
        "I_RectangleMisc",
        "IR_Announcement",
        "P_RegionSpeedLim",
        "P_RegionSpeedLimRev",
        "P_RampSpeedLim",
        "P_RegionNoParking",
        "P_RegionNoParkingRev",
        "P_RegionNoLongParking",
        "P_RegionNoLongParkingRev",
        "IR_LinearguideIndicate",
        "IR_LinearguideHighway",
        "IR_LinearguideWarning",
        "IR_ETCLanesKeepDistance",
    ],
}

# 标注返回的json中的关键字
task_key_word = "traffic_sign"


# ---------------------------- task dataloader ----------------------------- #
dataset = HorizonDataset(projects=["unknown"], tasks=task)

train_dataloader = build_dataloader(
    dataset=dataset.build_dataset(
        mode="train",
        transforms=transforms["train_cls"],  # task_transforms,
        fast_debug=fast_debug_dataset_number,
        use_all_data=use_all_data,
    ),
    mode="train",
    batch_size_per_gpu=batch_size_per_gpu["train_cls"],
    num_workers=num_workers["train"],
    is_iterabledataset=True,
)
val_dataloader = build_dataloader(
    dataset=dataset.build_dataset(
        mode="val", transforms=transforms["val_cls"]
    ),
    mode="val",
    batch_size_per_gpu=batch_size_per_gpu["val_cls"],
    num_workers=num_workers["val"],
    is_iterabledataset=True,
)

# ------------------------------ task model -------------------------------- #
# This block defines the task network which is built on one pre-defined network
# in the `models` directory
inputs = dict(
    train=copy.deepcopy(task_inputs["train_cls"]),
    val=copy.deepcopy(task_inputs["val_cls"]),
    test=copy.deepcopy(task_inputs["test"]),
    infer=dict(),
)


def get_model(
    backbone=backbone,
    task_name=task_name,
    mode="train",
    **kwargs,
):
    bn_kwargs = dict(eps=1e-5, momentum=0.1)
    in_channel_list = backbone["stride2channels"]
    backbone = copy.deepcopy(backbone["backbone"])
    neck = dict(
        neck=torch.nn.Identity(),
        stride2channels=in_channel_list,
    )
    task_model = build_attribute_classifier(
        backbone,
        neck,
        task_name,
        bn_kwargs,
        num_classes,
        mode,
        attr_type_list,
        attr_type_value,
        ignore_idxs,
    )
    return task_model


# ------------------------------ task metrics ------------------------------ #
train_metric_updater, val_metric_updater = get_metrics(
    task_name,
    attr_type_list=attr_type_list,
    attr_type_value=attr_type_value,
    ignore_idxs=ignore_idxs,
)
