import glob
import json
import logging
import os
import re
from typing import Dict, List, Optional, Tuple, Union

import numpy as np
from easydict import EasyDict

from hat.utils.apply_func import _as_list

logger = logging.getLogger(__name__)


def get_pack_list(anno_path: str, camera_names: List[str]) -> List:
    """Get image and anno list.

    Args:
        anno_path:
            Annotation path generated by auto_label, coco format.
        camera_names:
            List of camera names.

    Return:
        Pack list.
            List of (image, anno)
    """

    anno_files = glob.glob(os.path.join(anno_path, "*.json"))
    with open(anno_files[0], "r") as f:
        json_anno = json.load(f)
    images, annotations = json_anno["images"], json_anno["annotations"]

    imgid2anno = {}
    for im_info in images:
        for camera_name in camera_names:
            if camera_name in im_info["image_key"]:
                imgid2anno[im_info["id"]] = {
                    "meta": im_info,
                    "objects": [],
                    "image_key": os.path.basename(im_info["image_source"]),
                }

    for anno in annotations:
        img_id = anno["image_id"]
        if img_id in imgid2anno:
            imgid2anno[img_id]["objects"] += [anno]

    pack_list = [
        (os.path.join(anno_path, "data", anno["image_key"]), anno)
        for anno in imgid2anno.values()
    ]

    logger.info("Found %d images" % len(pack_list))

    return pack_list


def ls_img_folder_and_anno_file(
    root_path: Union[List[str], str],
    anno_ext: str = ".json",
    recursive: bool = True,
    excluded_annos_pattern: Union[List[str], Tuple[str]] = None,
) -> List[Tuple]:
    """
    List image folders and their annotation files recursively.

    Data should be organize in:

    .. code-block:: none

        root_path[0]/
            image_folder1
            image_folder1.json
            image_folder2
            image_folder2.json
        root_path[1]/
            image_folder3
            image_folder3.json
            ...

    annotation files in ``excluded_annos`` will be ignored.

    Args:
        root_path:
            Root paths for listing. [root_path1, root_path2...].
        anno_ext:
            The extension of annotation files.
        recursive:
            Whether to list recursively.
        excluded_annos:
            Paths of excluded annotation files.

    Returns:
        folder_anno_pair_list:
            Return list of (image_folder, anno_file) pairs.

    Examples:
        ls_img_folder_and_anno_file(['root_path1', 'root_path2', ...],
            anno_ext='.json', recursive=True,
            excluded_annos=['/path/to/excluded_anno1.json', ...]
    """

    root_path = _as_list(root_path)
    if excluded_annos_pattern is not None:
        excluded_annos_pattern = re.compile(excluded_annos_pattern)

    if not anno_ext.startswith("."):
        anno_ext = "." + anno_ext
    image_folder_list = []
    anno_file_list = []

    def _search_one_path(one_path):
        one_path = os.path.expanduser(one_path)
        anno_files = glob.glob(
            one_path + "/**/*" + anno_ext, recursive=recursive
        )
        for anno_file in anno_files:
            # check abs path
            if excluded_annos_pattern is not None:
                if excluded_annos_pattern.match(anno_file):
                    logger.info("ignore annotation %s" % anno_file)
                    continue
            img_folder = anno_file.replace(anno_ext, "")
            if not os.path.exists(img_folder) or not os.path.exists(anno_file):
                continue
            image_folder_list.append(img_folder)
            anno_file_list.append(anno_file)

    for one_path in root_path:
        _search_one_path(one_path)

    folder_anno_pair_list = list(zip(image_folder_list, anno_file_list))
    return folder_anno_pair_list


def get_colors_and_class_names_for_lane_parsing(color_map: Dict):
    """
    Get class name list and the corresponding color list for lane parsing task.

    Args:
        color_map:
            The segmentation color map.
    """
    colors, clsnames = get_colors_and_class_names_for_parsing(color_map)
    colors[255, :, :] = [255, 0, 0]  # lane parsing default class

    return colors, clsnames


def get_colors_and_class_names_for_parsing(color_map):
    """Get class name list and the corresponding color list.

    Args:
        color_map: dict
            The segmentation color map.
    """
    colors = np.zeros((256, 1, 3), dtype=np.uint8)
    clsnames = []
    for i, (class_name, color) in enumerate(color_map.items()):
        colors[i, :, :] = color
        clsnames.append(class_name)

    return colors, clsnames


def str_to_bool(s):
    s = s.lower()
    if s in ["true", "t", "1"]:
        return True
    elif s in ["false", "f", "0"]:
        return False
    else:
        raise ValueError("Invalid value %s" % s)


def set_pack_env(
    num_worker: int = 16,
    allow_missing: Optional[bool] = False,
    skip_invalid: Optional[bool] = False,
    overwrite: Optional[bool] = False,
    verbose: Optional[bool] = False,
    pipeline_test: Optional[bool] = False,
):
    """
    Set environment for auto matrix data packer tools.

    Args:
        num_worker:
            Parallel numbers, by default 16
        allow_missing:
            Whether allowing image provided in annotations by does not exists,
            by default False
        skip_invalid:
            Whether skip invalid images, e.g., broken image, by default False
        overwrite:
            Whether to overwrite existing records, by default False
        verbose:
            Whether to verbose, by default False
        pipeline_test:
            Whether in pipeline test mode, by default False
    """

    os.environ.update(
        {
            "PACK_NUM_WORKER": str(num_worker),
            "PACK_ALLOW_MISSING": str(allow_missing),
            "PACK_SKIP_INVALID": str(skip_invalid),
            "PACK_OVERWRITE": str(overwrite),
            "PACK_VERBOSE": str(verbose),
            "PACK_PIPELINE_TEST": str(pipeline_test),
        }
    )


def get_default_pack_args_from_environment(
    default_num_worker=16,
    default_allow_missing="False",
    default_skip_invalid="False",
    default_overwrite="False",
    default_verbose="False",
):
    """
    Get arguments from data packer tools environment.

    Args:
        **kwargs :
            Please see :py:func:`set_pack_env`
    """
    num_worker = int(os.environ.get("PACK_NUM_WORKER", default_num_worker))

    allow_missing = str_to_bool(
        os.environ.get("PACK_ALLOW_MISSING", default_allow_missing)
    )

    skip_invalid = str_to_bool(
        os.environ.get("PACK_SKIP_INVALID", default_skip_invalid)
    )

    overwrite = str_to_bool(
        os.environ.get("PACK_OVERWRITE", default_overwrite)
    )

    verbose = str_to_bool(os.environ.get("PACK_VERBOSE", default_verbose))

    pipeline_test = str_to_bool(os.environ.get("PACK_PIPELINE_TEST", "False"))

    return EasyDict(
        {
            "num_worker": num_worker,
            "allow_missing": allow_missing,
            "skip_invalid": skip_invalid,
            "overwrite": overwrite,
            "verbose": verbose,
            "pipeline_test": pipeline_test,
        }
    )
