import argparse
import csv
import re


def convert_to_list(html_file):
    with open(html_file, "r") as f:
        for line in f.readlines():
            line = line.strip()
            res = re.match(r"nodes = JSON.parse\(\'(.*)\'\);", line)
            if res:
                res = eval(res.group(1))
                return res
    return None


def convert_to_dict(line_info):
    res = {}
    for line in line_info:
        tmp = line.split(":")
        res[tmp[0].strip()] = tmp[1].strip()
    return res


def parse_latency(html_file, latency_file, csv_file):
    with open(csv_file, mode="w") as out_csv:
        csv_writer = csv.writer(
            out_csv, delimiter=",", quotechar='"', quoting=csv.QUOTE_MINIMAL
        )
        heads = [
            "layer id",
            "layer type",
            "kernel size",
            "stride",
            "input shape",
            "output shape",
            "group base",
            "group num",
            "latency(us)",
        ]
        csv_writer.writerow(heads)
        res_infos = convert_to_list(html_file)
        with open(latency_file, "r") as f:
            latency_infos = f.readlines()
        assert res_infos is not None and len(res_infos) == len(
            latency_infos
        ), "Parsing html error!"
        for line_res, line_latency in zip(res_infos, latency_infos):
            result = [""] * len(heads)
            layer_info = convert_to_dict(line_res["parameters"])
            # layer id
            result[0] = layer_info["ID"]
            # layer type
            result[1] = line_res["name"]
            # kernel size
            if "<br/>kernel" in layer_info.keys():
                result[2] = layer_info["<br/>kernel"]
            # stride
            if (
                "<br/>stride x" in layer_info.keys()
                and "<br/>stride y" in layer_info.keys()
            ):
                stride_x = int(layer_info["<br/>stride x"])
                stride_y = int(layer_info["<br/>stride y"])
                result[3] = (stride_x, stride_y)
            # TODO: input shape
            # output shape
            result[5] = layer_info["<br/>Output Dims"]
            # group base & group num
            if "<br/>num filters:" in layer_info:
                filter = int(layer_info["<br/>num filters:"])
                groups = filter
                if "<br/>groups:" in layer_info:
                    groups = int(layer_info["<br/>groups:"])
                result[6] = filter / groups
                result[7] = groups
            # latency
            latency = line_latency.split(":")[1].strip()
            result[8] = latency.split(" ")[0]
            csv_writer.writerow(result)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--html_path",
        type=str,
        required=True,
        help="The html file generated by snpe-diagview when visualize the dlc",
    )
    parser.add_argument(
        "--latency_path",
        type=str,
        required=True,
        help="The latency results generated by snpe-diagview",
    )
    parser.add_argument(
        "--out_csv_path",
        type=str,
        required=True,
        help="The csv path to save the results.",
    )
    args = parser.parse_args()
    parse_latency(args.html_path, args.latency_path, args.out_csv_path)
