#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import logging
import os
import re
import signal
import subprocess
import sys

from torch.distributed.elastic.multiprocessing.errors import ChildFailedError
from torch.distributed.run import main

logger = logging.getLogger()


def run_nccl_test():
    try:
        result = subprocess.run(
            "./nccl_check.sh",
            shell=True,
            capture_output=True,
            text=True,
            check=True,
            env=os.environ.copy(),
        )
    except subprocess.CalledProcessError as e:
        logger.warning(
            f"subprocess({e.cmd}) failed({e.returncode})! {e.output}.\n"
        )
        result = None
    if result:
        logger.warning(result.stdout)
    return result


if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    try:
        main()
    except ChildFailedError as e:
        logger.error("=" * 50 + " TORCHRUN FAILED" + "=" * 50)
        logger.error(f"torchrun raise ChildFailedError: ({str(e)})\n")
        logger.warning("=" * 50 + " TORCHRUN START NCCL_TEST" + "=" * 50)
        run_nccl_test()
        logger.warning("=" * 50 + " TORCHRUN NCCL_TEST END" + "=" * 50)
        os.killpg(os.getpgid(os.getpid()), signal.SIGKILL)
    except Exception as e:
        logger.error("=" * 50 + " TORCHRUN FAILED" + "=" * 50)
        logger.error(f"torchrun process failed: ({str(e)}).\n")
        raise e
