task_name: vehicle_light_classification
annokey_first_layer: vehicle
annokey_second_layer: VehicleLightStatus
eval_categorys: # 实际进行评测的类别
- LeftTurnLightOn
- RightTurnLightOn
- BrakeLightOn
- AllOff
- LeftTurnLightBrakeLightOn
- RightTurnLightBrakeLightOn
- ClearanceLampOn
- LeftRightTurnLightOn
- ReverseLampOn

full_image_as_bbox: false # 如果全图分类, 则设置为true

# 9 classification
gt_to_eval_category: # 将标注属性转换为实际评测类别
  LeftTurnLightOn: LeftTurnLightOn
  RightTurnLightOn: RightTurnLightOn
  BrakeLightOn: BrakeLightOn
  AllOff: AllOff
  LeftTurnLightBrakeLightOn: LeftTurnLightBrakeLightOn
  RightTurnLightBrakeLightOn: RightTurnLightBrakeLightOn
  ClearanceLampOn: ClearanceLampOn
  LeftRightTurnLightOn: LeftRightTurnLightOn
  ReverseLampOn: ReverseLampOn


ignores: # 如果gt中某个样本的attrs字典中包含以下任一字典, 则该样本将不要参与评测
- ignore: 'yes'
- hard_sample: 'yes'

# min_width: 43.4571 #CN0820
#min_width: 25.2 # CN0323
min_width: 75 # X8B

# 9 classification
pred_to_eval_category: # 将模型不同位置输出值映射到实际评测类别
  0: LeftTurnLightOn
  1: RightTurnLightOn
  2: BrakeLightOn
  3: AllOff
  4: LeftTurnLightBrakeLightOn
  5: RightTurnLightBrakeLightOn
  6: ClearanceLampOn
  7: LeftRightTurnLightOn
  8: ReverseLampOn

with_scores: true
score_process: raw # score处理方式, 支持softmax和raw两种方式, 其中raw为不进行处理
