v0.0.1:
  pipeline_test:
    4GD36_dense_freespace:
      4GD36_20220610:
pipeline_test:
  pipeline_test:
    UT263:
      UT263_20230815_D_parking_zhuxian_v5a_11v_sequential_4frame:
        sample_interval: 200
pipeline_testV2:
  ZHANGAIWU:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace:
              sample_interval: 100
# freespace v2
v1.1.1:
  BJ:
    UT0Q9_dense_freespace:
      FSD_Site_UT0Q9_20220529_v5a:
        sample_interval: 4
    H3165_dense_freespace:
      FSD_Site_H3165_20220518_v5a:
        sample_interval: 8
    4GD36_dense_freespace:
      FSD_Site_4GD36_20220531_v5a:
        sample_interval: 8
      FSD_Site_4GD36_20220610_v5a:
    UTHS6_dense_freespace:
      FSD_Site_UTHS6_20220915_v5a:
        sample_interval: 6

# 6v/11v mixed data
v1.1.2:
  BJ:
    UT0Q9_dense_freespace:
      FSD_Site_UT0Q9_20220529_v5a:
        sample_interval: 4
    H3165_dense_freespace:
      FSD_Site_H3165_20220518_v5a:
        sample_interval: 8
    4GD36_dense_freespace:
      FSD_Site_4GD36_20220531_v5a:
        sample_interval: 8
      FSD_Site_4GD36_20220610_v5a:
    UTHS6_dense_freespace:
      FSD_Site_UTHS6_20220915_v5a:
        sample_interval: 6
    # 11v data
    UT126_densse_freespace:
      FSD_Site_UT126_20220812_v5a_11v:
        sample_interval: 2
      FSD_Site_UT126_20220909_v5a_11v:
        sample_interval: 2
    UT263_densse_freespace:  
      FSD_Site_UT263_20220924_v5a_11v:

# 6v通用障碍物评测集 UTHS6 0921
v1.1.3:
  ZHANGAIWU:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace:

# 6v通用障碍物数据集集 UTHS6 0921大范围 (-51.2, -76.8, 153.6, 76.8)
v2.1.0:
  ZHANGAIWU_WIDE:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_val:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_train:

# 11v 静态标注wide range (-51.2, -76.8, 153.6, 76.8)
v2.1.1:
  STATIC_ANNO_WIDE_TOTAL:
    UT126:
      FSD_Site_UT126_20221018_v5a_wide_11v:
        sample_interval: 4
      FSD_Site_UT126_20220930_v5a_wide_11v:
      FSD_Site_UT126_20221024_v5a_wide_11v:
        sample_interval: 2
    UTHS6:
      FSD_Site_UTHS6_20221024_v5a_wide_11v:
        sample_interval: 6
      FSD_Site_UTHS6_20221101_v5a_wide_11v:
        sample_interval: 6
    UT0Q9:
      FSD_Site_UT0Q9_20221010_v5a_wide_11v:
        sample_interval: 6
    UT263:
      FSD_Site_UT263_20221030_v5a_wide_11v:
        sample_interval: 2
    UT3J5:
      FSD_Site_UT3J5_20221016_v5a_wide_11v:
        sample_interval: 3

# 部分6v通用障碍物数据集 UTHS6 0921大范围 (-51.2, -76.8, 153.6, 76.8)
v2.1.2_small_obstacle:
  ZHANGAIWU_WIDE:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_val:

v2.1.3_small_obstacle_11v:
  ZHANGAIWU_WIDE:
    UT126:
      FSD_Site_UT126_20220810_01_11v:
      FSD_Site_UT126_20220810_0201_11v:
      FSD_Site_UT126_20220810_0202_11v:
      FSD_Site_UT126_20220810_0301_11v:
      FSD_Site_UT126_20220810_0302_11v:
      FSD_Site_UT126_20220810_10_11v:

v2.1.4_small_obstacle_total:
  ZHANGAIWU_WIDE:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_val:
    UT126:
      FSD_Site_UT126_20220810_01_11v:
      FSD_Site_UT126_20220810_0201_11v:
      FSD_Site_UT126_20220810_0202_11v:
      FSD_Site_UT126_20220810_0301_11v:
      FSD_Site_UT126_20220810_0302_11v:
      FSD_Site_UT126_20220810_10_11v:

v2.1.4_small_obstacle_total_sequence:
  ZHANGAIWU_WIDE:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_val_sequential:
    UT126:
      0208_FSD_Site_UT126_20220810_0202_11v_sequential:
      0208_FSD_Site_UT126_20220810_0301_11v_sequential:
      0208_FSD_Site_UT126_20220810_0302_11v_sequential:
      0208_FSD_Site_UT126_20220810_10_11v_sequential:
      0208_FSD_Site_UT126_20220810_01_11v_sequential:
      0208_FSD_Site_UT126_20220810_0201_11v_sequential:

v2.2.0:
  PARKING_MANUAL_whitelist_speedbump:  # 人工标注泊车减速带评测集
    UT126:
      val_parkinglock_speedbump_UT126_20221103_D_v5a_autolabel_freespace_11v_sequential_total:
        sample_interval: 10
      val_parkinglock_speedbump_UT126_20221110_D_v5a_autolabel_freespace_11v_sequential_total:
        sample_interval: 10
      val_parkinglock_speedbump_UT126_20221113_D_v5a_autolabel_freespace_11v_sequential_total:
        sample_interval: 10
      val_parkinglock_speedbump_UT126_20221029_D_v5a_autolabel_freespace_11v_sequential_total:
        sample_interval: 10

v2.2.1:
  PARKING_MANUAL_whitelist_parkinglock: # 人工标注泊车地锁评测集
    UT126:
      val_parkinglock_speedbump_vparkinglock_UT126_20221029_D_v5a_autolabel_freespace_11v_sequential_total:
        sample_interval: 3
      val_parkinglock_speedbump_vparkinglock_UT126_20221111_D_v5a_autolabel_freespace_11v_sequential_total:
        sample_interval: 3
      val_parkinglock_speedbump_vparkinglock_UT126_20221112_D_v5a_autolabel_freespace_11v_sequential_total:
        sample_interval: 3

v2.2.2:
  PARKING_MANUAL_whitelist_parkingrod: # 人工标注泊车限位杆评测集
    UT126:
      val_parking_rod_UT126_20221029_D_v5a_autolabel_freespace_11v_sequential_total:
        sample_interval: 10
      val_parking_rod_UT126_20221103_D_v5a_autolabel_freespace_11v_sequential_total:
        sample_interval: 10

v2.2.3:
  PARKING_MANUAL_VAL_DATA: # 人工标注泊车评测集
    LS830:
      LS830_20230318_D_parking_artificial_sequential_v5a_11v_total_gt:
        sample_interval: 5
      LS830_20230320_D_parking_artificial_sequential_v5a_11v_total_gt:
        sample_interval: 5
      LS830_20230308_D_parking_artificial_sequential_v5a_11v_total_gt:
        sample_interval: 5
      LS830_20230309_D_parking_artificial_sequential_v5a_11v_total_gt:
        sample_interval: 2
      LS830_20230316_D_parking_artificial_sequential_v5a_11v_total_gt:
        sample_interval: 5
    UT0F3:
      UT0F3_20230317_D_parking_artificial_sequential_v5a_11v_total_gt:
        sample_interval: 5
      UT0F3_20230320_D_parking_artificial_sequential_v5a_11v_total_gt:
        sample_interval: 5
    UT0Q9:
      UT0Q9_20230324_D_parking_artificial_sequential_v5a_11v_total_gt:
        sample_interval: 5

# 7v BYD data with wide range gt (-51.2, -80.0, 153.6, 80.0)
v3.1.0:
  BYD_WIDE:
    BYD18:
      FSD_Site_BYD18_20221114_v5a_autolabel_freespace_7v:

# 7v BYD data + 6v通用障碍物数据集集
v3.2.0:
  BYD_WIDE:
    BYD18:
      FSD_Site_BYD18_20221114_v5a_autolabel_freespace_7v:
  ZHANGAIWU_WIDE:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_val:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_train:

# 7v BYD data + 部分6v通用障碍物数据集集
v3.3.0:
  BYD_WIDE:
    BYD18:
      FSD_Site_BYD18_20221114_v5a_autolabel_freespace_7v:
  ZHANGAIWU_WIDE:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_val:

# 增加泊车质检数据
v3.4.0_all:
  BYD_WIDE:
    BYD18:
      FSD_Site_BYD18_20221114_v5a_autolabel_freespace_7v:
  ZHANGAIWU_WIDE:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_val:
  PARKING_QUALITY_CHECK_V1:
    UT126:
      20230315_UT126_20220913_D_v5a_autolabel_freespace_11v:

# 11v数据for fisheye model
v3.5.0_all:
  AUTO_LABEL_QUALITY_CHECK_ZHUXIAN:
    LS912:
      FSD_Site_LS912_20230220_sequential_drive_zhuxian_v5a_11v_val:
  PARKING_QUALITY_CHECK_V1:
    UT263:
      UT263_20230308_D_sequential_drive_zhuxian_v5a_11v:
        sample_interval: 2
  ZHANGAIWU_WIDE:
    UT126:
      FSD_Site_UT126_20220810_01_11v:
      FSD_Site_UT126_20220810_0201_11v:
      FSD_Site_UT126_20220810_0202_11v:
      FSD_Site_UT126_20220810_0301_11v:
      FSD_Site_UT126_20220810_0302_11v:
      FSD_Site_UT126_20220810_10_11v:

v3.5.0_all_driving:
  AUTO_LABEL_QUALITY_CHECK_ZHUXIAN:
    LS912:
      FSD_Site_LS912_20230220_sequential_drive_zhuxian_v5a_11v_val:
  ZHANGAIWU_WIDE:
    UT126:
      FSD_Site_UT126_20220810_01_11v:
      FSD_Site_UT126_20220810_0201_11v:
      FSD_Site_UT126_20220810_0202_11v:
      FSD_Site_UT126_20220810_0301_11v:
      FSD_Site_UT126_20220810_0302_11v:
      FSD_Site_UT126_20220810_10_11v:

v3.5.0_all_parking:
  PARKING_QUALITY_CHECK_V1:
    UT263:
      UT263_20230308_D_sequential_drive_zhuxian_v5a_11v:
        sample_interval: 2
  PARKING_QUALITY_CHECK_V1_filter_ele_vismask:
    LS830:
      LS830_20230411_D_parking_zhuxian_v5a_11v:
    UT263:
      UT263_20230327_D_parking_zhuxian_v5a_11v:
    UT370:
      UT370_20230601_D_parking_zhuxian_v5a_11v:

v3.6.0_all_temporal:
  FILTER_V4.7_BAD_DATA_filter_ele_vismask:
    BYD18:
      20230203_FSD_Site_BYD18_20221205_v5a_autolabel_freespace_drop_stillness_7v_after_rejectscreen_iou_0309_total_gt:
    BYD19:
      20230203_FSD_Site_BYD19_20221108_v5a_autolabel_freespace_drop_stillness_7v_after_rejectscreen_iou_0309_total_gt:
    BYD72:
      FSD_Site_BYD72_20221128_v5a_v2_autolabel_freespace_7vscreen_iou_0309_total_gt:
        sample_interval: 5
  PARKING_QUALITY_CHECK_V1_filter_ele_vismask:
    UT126:
      20230407_UT126_20230210_D_v5a_autolabel_freespace_11v_total_gt:
  ZHANGAIWU_WIDE:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_val_sequential:
    UT126:
      0208_FSD_Site_UT126_20220810_0202_11v_sequential:
      0208_FSD_Site_UT126_20220810_0301_11v_sequential:
      0208_FSD_Site_UT126_20220810_0302_11v_sequential:
      0208_FSD_Site_UT126_20220810_10_11v_sequential:
      0208_FSD_Site_UT126_20220810_01_11v_sequential:
      0208_FSD_Site_UT126_20220810_0201_11v_sequential:

v3.6.0_all_temporal_driving:
  FILTER_V4.7_BAD_DATA_filter_ele_vismask:
    BYD19:
      20230203_FSD_Site_BYD19_20221108_v5a_autolabel_freespace_drop_stillness_7v_after_rejectscreen_iou_0309_total_gt:
  AUTO_LABEL_QUALITY_CHECK_ZHUXIAN:
    LX165:
      FSD_Site_LX165_20230328_drive_zhuxian_v5a_sequential_11v:
      FSD_Site_LX165_20230609_drive_zhuxian_v5a_sequential_11v:
  ZHANGAIWU_WIDE:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_val_sequential:
    UT126:
      0208_FSD_Site_UT126_20220810_0202_11v_sequential:
      0208_FSD_Site_UT126_20220810_0301_11v_sequential:
      0208_FSD_Site_UT126_20220810_0302_11v_sequential:
      0208_FSD_Site_UT126_20220810_10_11v_sequential:
      0208_FSD_Site_UT126_20220810_01_11v_sequential:
      0208_FSD_Site_UT126_20220810_0201_11v_sequential:

v3.6.0_all_temporal_parking:
  PARKING_QUALITY_CHECK_V1_filter_ele_vismask:
    UT263:
      UT263_20230515_D_parking_zhuxian_v5a_sequential_11v:
      UT263_20230616_D_parking_zhuxian_v5a_sequential_11v:

v3.7.0_all_temporal_driving:
  FILTER_V4.7_BAD_DATA_filter_ele_vismask:
    BYD19:
      20230203_FSD_Site_BYD19_20221108_v5a_autolabel_freespace_drop_stillness_7v_after_rejectscreen_iou_0309_total_gt:
  AUTO_LABEL_QUALITY_CHECK_ZHUXIAN:
    LX165:
      FSD_Site_LX165_20230328_drive_zhuxian_v5a_sequential_11v:
      FSD_Site_LX165_20230609_drive_zhuxian_v5a_sequential_11v:
    LS912:
      FSD_Site_LS912_20230401_drive_zhuxian_v5a_sequential_11v:
  ZHANGAIWU_WIDE:
    UTHS6:
      FSD_Site_UTHS6_20220921_freespace_wide_artificial_val_sequential:
    UT126:
      0208_FSD_Site_UT126_20220810_0202_11v_sequential:
      0208_FSD_Site_UT126_20220810_0301_11v_sequential:
      0208_FSD_Site_UT126_20220810_0302_11v_sequential:
      0208_FSD_Site_UT126_20220810_10_11v_sequential:
      0208_FSD_Site_UT126_20220810_01_11v_sequential:
      0208_FSD_Site_UT126_20220810_0201_11v_sequential:

v3.7.0_all_temporal_parking:
  PARKING_QUALITY_CHECK_V1_filter_ele_vismask:
    UT263:
      UT263_20230515_D_parking_zhuxian_v5a_sequential_11v:
      UT263_20230616_D_parking_zhuxian_v5a_sequential_11v:
    LS830:
      LS830_20230418_D_parking_zhuxian_v5a_sequential_11v:
      LS830_20230419_D_parking_zhuxian_v5a_sequential_11v:


v3.7.1_all_parking:
  PARKING_QUALITY_CHECK_V1:
    UT263:
      UT263_20230308_D_sequential_drive_zhuxian_v5a_11v:
        sample_interval: 2
  PARKING_QUALITY_CHECK_V1_filter_ele_vismask:
    UT263:
      UT263_20230515_D_parking_zhuxian_v5a_sequential_11v:
      UT263_20230616_D_parking_zhuxian_v5a_sequential_11v:
    LS830:
      LS830_20230418_D_parking_zhuxian_v5a_sequential_11v:
      LS830_20230419_D_parking_zhuxian_v5a_sequential_11v:

# total nums: 8900
v1.0.0_parking_overground_rough:
  PARKING_QUALITY_CHECK_V1_filter_ele_vismask:
    UT263:
      UT263_20230515_D_parking_zhuxian_v5a_sequential_11v:
    LS830:
      LS830_20230418_D_parking_zhuxian_v5a_sequential_11v:
      LS830_20230419_D_parking_zhuxian_v5a_sequential_11v:
  parking_20240117:
    UT0T1:
      UT0T1_20230923:
        sample_interval: 2

# total nums: 11084
v1.0.0_parking_underground_rough:
  parking_20240117:
    UT370:
      UT370_20231012: 
        sample_interval: 2
      UT370_20231011:
        sample_interval: 2
      UT370_20231008:
        sample_interval: 2
      UT370_20230925:
        sample_interval: 2
      UT370_20230926:
        sample_interval: 2

# EK underground val sets
# underground: 6728 frames
v1.0.0_ek_parking_underground:
  parking_20240123:
    HBEK383:
      HBEK383_20231207_underground: null
      HBEK383_20231221_underground: null
      HBEK383_20231222_underground: null
      HBEK383_20231223_underground: null
      HBEK383_20231224_underground: null
      HBEK383_20231210_underground: null
      HBEK383_20231211_underground: null
      HBEK383_20231212_underground: null
      HBEK383_20231213_underground: null
      HBEK383_20231214_underground: null
      HBEK383_20231216_underground: null
      HBEK383_20231217_underground: null
      HBEK383_20231218_underground: null
      HBEK383_20231219_underground: null
      HBEK383_20231220_underground: null

# EK ground val sets
# ground: 554 frames
v1.0.0_ek_parking_ground:
  parking_20240123:
    HBEK383:
      HBEK383_20231206_ground: null
      HBEK383_20231207_ground: null
      HBEK383_20231209_ground: null
      HBEK383_20231210_ground: null

# v1.0_5v_small_obstacle_temporal:
#   ZHANGAIWU_WIDE:
#     UTHS6:
#       FSD_Site_UTHS6_20220921_freespace_wide_artificial_val_sequential:

# BYD人工标注数据
v_sunny:
  MANUAL_ANNO_TEST:
    BYD72:
      FSD_Site_BYD72_20230120_v5a_val_freespace_artificial_sunny_day:
      FSD_Site_BYD72_20230202_v5a_val_freespace_artificial_sunny_day:
      FSD_Site_BYD72_20230203_v5a_val_freespace_artificial_sunny_day:
    BYD19:
      FSD_Site_BYD19_20230118_v5a_val_freespace_artificial_sunny_day:
      FSD_Site_BYD19_20230201_v5a_val_freespace_artificial_sunny_day:
      FSD_Site_BYD19_20230204_v5a_val_freespace_artificial_sunny_day:
      FSD_Site_BYD19_20230210_v5a_val_freespace_artificial_sunny_day:
    BYD18:
      FSD_Site_BYD18_20230129_v5a_val_freespace_artificial_sunny_day:
      FSD_Site_BYD18_20230130_v5a_val_freespace_artificial_sunny_day:

v_cloudy:
  MANUAL_ANNO_TEST:
    BYD19:
      FSD_Site_BYD19_20221210_v5a_val_freespace_artificial_cloundy:
      FSD_Site_BYD19_20230113_v5a_val_freespace_artificial_cloundy:
    BYD18:
      FSD_Site_BYD18_20230210_v5a_val_freespace_artificial_cloundy:
      FSD_Site_BYD18_20230211_v5a_val_freespace_artificial_cloundy:

v_rainy:
  MANUAL_ANNO_TEST:
    BYD19:
      FSD_Site_BYD19_20221210_v5a_val_freespace_artificial_rain:

v_night:
  MANUAL_ANNO_TEST:
    UT1R3:
      night_xinche_0420_FSD_Site_UT1R3_20221102_v5a_autolabel_freespace_11v:
      night_xinche_0420_FSD_Site_UT1R3_20221125_v5a_autolabel_freespace_11v:
      night_xinche_0420_FSD_Site_UT1R3_20221201_v5a_autolabel_freespace_11v:
      night_xinche_0420_FSD_Site_UT1R3_20221215_v5a_autolabel_freespace_11v:
      night_xinche_0420_FSD_Site_UT1R3_20221228_v5a_autolabel_freespace_11v:
    UT263:
      night_xinche_0420_FSD_Site_UT263_20221118_v5a_autolabel_freespace_11v:
    UT3J5:
      night_xinche_0420_FSD_Site_UT3J5_20221126_v5a_autolabel_freespace_11v:
    BYD72:
      FSD_Site_BYD72_20221128_v5a_val_freespace_artificial_night:
      FSD_Site_BYD72_20230116_v5a_val_freespace_artificial_night:
      FSD_Site_BYD72_20230203_v5a_val_freespace_artificial_night:
    BYD19:
      FSD_Site_BYD19_20221210_v5a_val_freespace_artificial_night:
      FSD_Site_BYD19_20230201_v5a_val_freespace_artificial_night:
    BYD18:
      FSD_Site_BYD18_20230129_v5a_val_freespace_artificial_night:
      FSD_Site_BYD18_20230211_v5a_val_freespace_artificial_night:
