from c385_x3c_parking_resize_4 import task_threshold  # noqa

task_threshold.update(
    dict(
        person_detection=dict(
            threshold=dict(
                report_type="DetEvalReport",
                metric_type="ThresholdAtMaxDetRate",
                metric_kwargs=dict(),
            ),
            datasets=[
                dict(
                    dataset_id=6029351,
                    setting_names=[
                        "all_region-det-ped_5cam_forward0m_50",
                    ],
                ),
            ],
        ),
        cyclist_detection=dict(
            threshold=dict(
                report_type="DetEvalReport",
                metric_type="ThresholdAtMaxDetRate",
                metric_kwargs=dict(),
            ),
            datasets=[
                dict(
                    dataset_id=6028935,
                    setting_names=[
                        "all_region-det-cyclist_5cam_forward0m_50",
                    ],
                ),
            ],
        ),
        # 3D
        vehicle_roi_3d=dict(
            threshold=dict(
                report_type="DetEvalReport",
                metric_type="ThresholdAtMaxDetRate",
                metric_kwargs=dict(),
            ),
            datasets=[
                dict(
                    dataset_id=6029920,
                    setting_names=[
                        "5cam_0-50m_IoU0.5.yaml",
                    ],
                ),
            ],
        ),
        person_roi_3d=dict(
            threshold=dict(
                report_type="DetEvalReport",
                metric_type="ThresholdAtMaxDetRate",
                metric_kwargs=dict(),
            ),
            datasets=[
                dict(
                    dataset_id=6030224,
                    setting_names=[
                        "5cam_0-50m_IoU0.1.yaml",
                    ],
                ),
            ],
        ),
        cyclist_roi_3d=dict(
            threshold=dict(
                report_type="DetEvalReport",
                metric_type="ThresholdAtMaxDetRate",
                metric_kwargs=dict(),
            ),
            datasets=[
                dict(
                    dataset_id=6029998,
                    setting_names=[
                        "5cam_0-50m_IoU0.1.yaml",
                    ],
                ),
            ],
        ),
    )
)
