task_threshold = dict(
    # 4PE
    vehicle_detection=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            # 常规
            dict(
                dataset_id=6036727,
                setting_names=[
                    "all_region-det-veh-full_5cam_forward0m_40",
                ],
            ),
            # 眩光
            dict(
                dataset_id=6037953,
                setting_names=[
                    "all_region-det-veh-full_5cam_car_night_light_forward0m_40",  # noqa
                ],
            ),
        ],
    ),
    rear_detection=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6036105,
                setting_names=[
                    "all_region-det-veh-rear_5cam_forward0m_40",
                ],
            ),
        ],
    ),
    person_detection=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6036835,
                setting_names=[
                    "all_region-det-ped_5cam_forward0m_20",
                ],
            ),
        ],
    ),
    cyclist_detection=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6036837,
                setting_names=[
                    "all_region-det-cyclist_5cam_forward0m_20",
                ],
            ),
        ],
    ),
    # 2PE
    vehicle_wheel_detection=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            # dict(
            #     dataset_id=6029565,
            #     setting_names=[
            #         "all_region-det-veh-wheel_5cam_forward0m_40",
            #     ],
            # ),
        ],
    ),
    rear_plate_detection=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6037582,
                setting_names=[
                    "plate_minH20_iou0.5_ig0.3",
                ],
            ),
        ],
    ),
    person_face_detection=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6034106,
                setting_names=[
                    "face_minH32_iou0.5",
                ],
            ),
        ],
    ),
    # 3D
    vehicle_roi_3d=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6036019,
                setting_names=[
                    "5cam_0-30m_IoU0.5.yaml",
                ],
            ),
        ],
    ),
    person_roi_3d=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6036046,
                setting_names=[
                    "5cam_0-30m_IoU0.1.yaml",
                ],
            ),
        ],
    ),
    cyclist_roi_3d=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6036008,
                setting_names=[
                    "5cam_0-30m_IoU0.1.yaml",
                ],
            ),
        ],
    ),
)
