from suv_x3c_day_resize_4 import task_threshold

task_threshold.update(
    dict(
        person_detection=dict(
            threshold=dict(
                report_type="DetEvalReport",
                metric_type="ThresholdAtMaxDetRate",
                metric_kwargs=dict(),
            ),
            datasets=[
                dict(
                    dataset_id=6041581,
                    setting_names=[
                        "all_region-det-ped_5cam_forward0m_50",
                    ],
                ),
            ],
        ),
        cyclist_detection=dict(
            threshold=dict(
                report_type="DetEvalReport",
                metric_type="ThresholdAtMaxDetRate",
                metric_kwargs=dict(),
            ),
            datasets=[
                dict(
                    dataset_id=6041583,
                    setting_names=[
                        "all_region-det-cyclist_5cam_forward0m_50",
                    ],
                ),
            ],
        ),
        # 3D
        vehicle_roi_3d=dict(
            threshold=dict(
                report_type="DetEvalReport",
                metric_type="ThresholdAtMaxDetRate",
                metric_kwargs=dict(),
            ),
            datasets=[
                dict(
                    dataset_id=6042183,
                    setting_names=[
                        "5cam_0-50m_IoU0.5.yaml",
                    ],
                ),
            ],
        ),
        person_roi_3d=dict(
            threshold=dict(
                report_type="DetEvalReport",
                metric_type="ThresholdAtMaxDetRate",
                metric_kwargs=dict(),
            ),
            datasets=[
                dict(
                    dataset_id=6042192,
                    setting_names=[
                        "5cam_0-50m_IoU0.1.yaml",
                    ],
                ),
            ],
        ),
        cyclist_roi_3d=dict(
            threshold=dict(
                report_type="DetEvalReport",
                metric_type="ThresholdAtMaxDetRate",
                metric_kwargs=dict(),
            ),
            datasets=[
                dict(
                    dataset_id=6042195,
                    setting_names=[
                        "5cam_0-50m_IoU0.1.yaml",
                    ],
                ),
            ],
        ),
    )
)
