task_threshold = dict(
    vehicle_detection=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6037439,
                setting_names=[
                    "all_region-det-veh-full_pinhole_rear_forward0m_70",
                ],
            ),
        ],
    ),
    vehicle_roi_3d=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6036773,
                setting_names=[
                    "4cam_0-50m_IoU0.5.yaml",
                ],
            ),
        ],
    ),
    person_detection=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6038688,
                setting_names=[
                    "all_region-det-ped_pinhole_rear_forward0m_50",
                ],
            ),
        ],
    ),
    person_roi_3d=dict(
        threshold=dict(
            report_type="DetEvalReport",
            metric_type="ThresholdAtMaxDetRate",
            metric_kwargs=dict(),
        ),
        datasets=[
            dict(
                dataset_id=6040353,
                setting_names=[
                    "1cam_0-50m_IoU0.1.yaml",
                ],
            ),
        ],
    ),
)
