metrics = dict(
    # vehicle
    vehicle_detection=[
        dict(
            report_type="DetEvalReport",
            metric_type="MaxDetRate",
        ),
    ],
    vehicle_category_classification=[
        dict(
            report_type="MultiClassDetEvalReport",
            metric_type="AP",
        ),
    ],
    vehicle_occlusion_classification=[
        dict(
            report_type="MultiClassDetEvalReport",
            metric_type="AP",
        ),
    ],
    vehicle_truncation_classification=[
        dict(
            report_type="MultiClassDetEvalReport",
            metric_type="AP",
        ),
    ],
    vehicle_wheel_detection=[
        dict(
            report_type="DetEvalReport",
            metric_type="MaxDetRate",
        ),
    ],
    vehicle_ground_line=[
        dict(
            report_type="DetGDLReport",
            metric_type="AP",
        ),
    ],
    vehicle_flank=[
        dict(
            report_type="DetGDLReport",
            metric_type="AP",
        ),
    ],
    # rear
    rear_detection=[
        dict(
            report_type="DetEvalReport",
            metric_type="MaxDetRate",
        ),
    ],
    rear_plate_detection=[
        dict(
            report_type="DetEvalReport",
            metric_type="MaxDetRate",
        ),
    ],
    rear_occlusion_classification=[
        dict(
            report_type="MultiClassDetEvalReport",
            metric_type="AP",
        ),
    ],
    rear_part_classification=[
        dict(
            report_type="MultiClassDetEvalReport",
            metric_type="AP",
        ),
    ],
    # person
    person_detection=[
        dict(
            report_type="DetEvalReport",
            metric_type="MaxDetRate",
        ),
    ],
    person_face_detection=[
        dict(
            report_type="DetEvalReport",
            metric_type="MaxDetRate",
        ),
    ],
    person_occlusion_classification=[
        dict(
            report_type="MultiClassDetEvalReport",
            metric_type="AP",
        ),
    ],
    person_orientation_classification=[
        dict(
            report_type="MultiClassDetEvalReport",
            metric_type="AP",
        ),
    ],
    person_pose_classification=[
        dict(
            report_type="MultiClassDetEvalReport",
            metric_type="AP",
        ),
    ],
    # cyclist
    cyclist_detection=[
        dict(
            report_type="DetEvalReport",
            metric_type="MaxDetRate",
        ),
    ],
    cyclist_classification=[
        dict(
            report_type="MultiClassDetEvalReport",
            metric_type="AP",
        ),
    ],
    # seg
    default_segmentation=[
        dict(
            report_type="SegEvalReport",
            metric_type="MeanAcc",
        ),
        dict(
            report_type="SegEvalReport",
            metric_type="MeanIoU",
        ),
        dict(
            report_type="SegEvalReport",
            metric_type="ClassIoU",
        ),
    ],
    lane_segmentation=[
        dict(
            report_type="SegEvalReport",
            metric_type="MeanAcc",
        ),
        dict(
            report_type="SegEvalReport",
            metric_type="MeanIoU",
        ),
        dict(
            report_type="SegEvalReport",
            metric_type="ClassIoU",
        ),
    ],
    # 3D
    vehicle_roi_3d=[
        dict(
            report_type="DetEvalReport",
            metric_type="AP3D",
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Drot",
            target=0.8,
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Dxyp",
            target=0.8,
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Dxp",
            target=0.8,
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Dyp",
            target=0.8,
        ),
    ],
    person_roi_3d=[
        dict(
            report_type="DetEvalReport",
            metric_type="AP3D",
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Drot",
            target=0.8,
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Dxyp",
            target=0.8,
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Dxp",
            target=0.8,
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Dyp",
            target=0.8,
        ),
    ],
    cyclist_roi_3d=[
        dict(
            report_type="DetEvalReport",
            metric_type="AP3D",
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Drot",
            target=0.8,
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Dxyp",
            target=0.8,
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Dxp",
            target=0.8,
        ),
        dict(
            report_type="Det3DEvalReport",
            metric_type="Dyp",
            target=0.8,
        ),
    ],
)
