config_list = (
    "configs/nash/classification/efficientnasnetm_imagenet.py",
    "configs/nash/classification/efficientnasnets_imagenet.py",
    "configs/nash/classification/efficientnet_imagenet.py",
    "configs/nash/classification/mobilenetv1_imagenet.py",
    "configs/nash/classification/mobilenetv2_imagenet.py",
    "configs/nash/classification/resnet18_imagenet.py",
    "configs/nash/classification/resnet50_imagenet.py",
    "configs/nash/classification/mixvargenet_imagenet.py",
    "configs/nash/classification/horizon_swin_transformer_imagenet.py",
    "configs/nash/classification/vargconvnet_imagenet.py",
    "configs/nash/classification/vargnetv2_imagenet.py",
    "configs/nash/classification/torchvision/resnet18_imagenet.py",
    "configs/nash/classification/torchvision/resnet50_imagenet.py",
    "configs/nash/classification/torchvision/mobilenetv2_imagenet.py",
    "configs/nash/detection/retinanet/retinanet_vargnetv2_fpn_mscoco.py",
    "configs/nash/detection/yolov3/yolo_mobilenetv1_voc.py",
    "configs/nash/detection/yolov3/yolo_varg_darknet53_mscoco.py",
    "configs/nash/detection/fcos/fcos_efficientnetb0_mscoco.py",
    "configs/nash/detection/fcos/fcos_efficientnetb1_mscoco.py",
    "configs/nash/detection/fcos/fcos_efficientnetb2_mscoco.py",
    "configs/nash/detection/fcos/fcos_efficientnetb3_mscoco.py",
    "configs/nash/detection/detr/detr_efficientnetb3_mscoco.py",
    "configs/nash/detection/detr/detr_resnet50_mscoco.py",
    "configs/nash/detection/fcos3d/fcos3d_efficientnetb0_nuscenes.py",
    "configs/nash/detection/pointpillars/pointpillars_kitti_car.py",
    "configs/nash/detection/centerpoint/centerpoint_pointpillar_nuscenes.py",
    "configs/nash/lidar_multi_task/centerpoint_mixvargnet_multitask_nuscenes.py",  # noqa
    "configs/nash/segmentation/deeplabv3plus_efficientnetm0_cityscapes.py",
    "configs/nash/segmentation/deeplabv3plus_efficientnetm1_cityscapes.py",
    "configs/nash/segmentation/deeplabv3plus_efficientnetm2_cityscapes.py",
    "configs/nash/segmentation/fastscnn_efficientnetb0tiny_cityscapes.py",
    "configs/nash/segmentation/unet_mobilenetv1_cityscapes.py",
    "configs/nash/bev/bev_gkt_mixvargenet_multitask_nuscenes.py",
    "configs/nash/bev/bev_ipm_efficientnetb0_multitask_nuscenes.py",
    "configs/nash/bev/bev_lss_efficientnetb0_multitask_nuscenes.py",
    "configs/nash/bev/bev_ipm_4d_efficientnetb0_multitask_nuscenes.py",
    "configs/nash/bev/detr3d_efficientnetb3_nuscenes.py",
    "configs/nash/bev/petr_efficientnetb3_nuscenes.py",
    "configs/nash/lane_pred/ganet/ganet_mixvargenet_culane.py",
    "configs/nash/track_pred/motr_efficientnetb3_mot17.py",
    "configs/nash/track_pred/motr_efficientnetb3_mot17_qim.py",
    "configs/nash/disparity_pred/stereonet/stereonet_stereonetneck_sceneflow.py",  # noqa
    "configs/nash/opticalflow_pred/pwcnet/pwcnet_pwcnetneck_flyingchairs.py",
    "configs/nash/keypoint/keypoint_efficientnetb0_carfusion.py",
    "configs/nash/traj_pred/densetnt_vectornet_argoverse1.py",
    "configs/nash/disparity_pred/stereonet/stereonetplus_mixvargenet_sceneflow.py",  # noqa
)
