file_list = [
    "hat/version.py",
    "hat/callbacks/callbacks.py",
    "hat/callbacks/checkpoint.py",
    "hat/callbacks/exponential_moving_average.py",
    "hat/callbacks/freeze_bn.py",
    "hat/callbacks/grad_scale.py",
    "hat/callbacks/lr_updater.py",
    "hat/callbacks/metric_updater.py",
    "hat/callbacks/monitor.py",
    "hat/callbacks/online_model_trick.py",
    "hat/callbacks/save_traced.py",
    "hat/callbacks/tensorboard.py",
    "hat/callbacks/validation.py",
    "hat/callbacks/dump_data.py",
    "hat/core/*",
    "hat/data/collates/collates.py",
    "hat/data/collates/nusc_collates.py",
    "hat/data/dataloaders/passthrough_dataloader.py",
    "hat/data/datasets/batch_transform_dataset.py",
    "hat/data/datasets/cityscapes.py",
    "hat/data/datasets/data_packer.py",
    "hat/data/datasets/dataset_wrappers.py",
    "hat/data/datasets/flyingchairs_dataset.py",
    "hat/data/datasets/rand_dataset.py",
    "hat/data/datasets/imagenet.py",
    "hat/data/datasets/kitti2d.py",
    "hat/data/datasets/kitti3d.py",
    "hat/data/datasets/mscoco.py",
    "hat/data/datasets/voc.py",
    "hat/data/datasets/culane_dataset.py",
    "hat/data/datasets/sceneflow_dataset.py",
    "hat/data/datasets/nuscenes_dataset.py",
    "hat/data/datasets/culane_dataset.py",
    "hat/data/datasets/flyingchairs_dataset.py",
    "hat/data/datasets/mot17_dataset.py",
    "hat/data/datasets/carfusion_keypoints_dataset.py",
    "hat/data/datasets/argoverse_dataset.py",
    "hat/data/samplers/selected_sampler.py",
    "hat/data/samplers/dist_group_sampler.py",
    "hat/data/samplers/dist_cycle_sampler_multi_dataset.py",
    "hat/data/samplers/dist_sampler.py",
    "hat/data/samplers/dist_set_epoch_dataset_sampler.py",
    "hat/data/transforms/gaze/*",
    "hat/data/transforms/affine.py",
    "hat/data/transforms/bbox.py",
    "hat/data/transforms/classification.py",
    "hat/data/transforms/common.py",
    "hat/data/transforms/detection.py",
    "hat/data/transforms/functional_img.py",
    "hat/data/transforms/functional_target.py",
    "hat/data/transforms/segmentation.py",
    "hat/data/transforms/faceid.py",
    "hat/data/transforms/seq_transform.py",
    "hat/data/transforms/multi_views.py",
    "hat/data/transforms/grid_mask.py",
    "hat/data/transforms/lidar_utils/*",
    "hat/data/transforms/lidar.py",
    "hat/data/transforms/keypoints.py",
    "hat/data/utils.py",
    "hat/data/metas.py",
    "hat/engine/calibrator.py",
    "hat/engine/ddp_trainer.py",
    "hat/engine/dp_trainer.py",
    "hat/engine/launcher.py",
    "hat/engine/loop_base.py",
    "hat/engine/predictor.py",
    "hat/engine/processors/loss_collector.py",
    "hat/engine/processors/processor.py",
    "hat/engine/trainer.py",
    "hat/metrics/utils.py",
    "hat/metrics/acc.py",
    "hat/metrics/coco_detection.py",
    "hat/metrics/kitti2d_detection.py",
    "hat/metrics/kitti3d_detection.py",
    "hat/metrics/loss_show.py",
    "hat/metrics/mean_iou.py",
    "hat/metrics/metric.py",
    "hat/metrics/metric_optical_flow.py",
    "hat/metrics/voc_detection.py",
    "hat/metrics/metric_3dv_utils.py",
    "hat/metrics/nuscenes_metric.py",
    "hat/metrics/mot_metrics.py",
    "hat/metrics/metric_lane_detection.py",
    "hat/metrics/metric_keypoints.py",
    "hat/metrics/argoverse_metric.py",
    "hat/models/backbones/mobilenetv1.py",
    "hat/models/backbones/mobilenetv2.py",
    "hat/models/backbones/efficientnet.py",
    "hat/models/backbones/resnet.py",
    "hat/models/backbones/vargconvnet.py",
    "hat/models/backbones/vargnetv2.py",
    "hat/models/backbones/mixvargenet.py",
    "hat/models/backbones/horizon_swin_transformer.py",
    "hat/models/backbones/vargdarknet.py",
    "hat/models/backbones/contrib/*",
    "hat/models/backbones/vision_transformer.py",
    "hat/models/base_modules/*",
    "hat/models/model_convert/*",
    "hat/models/losses/cross_entropy_loss.py",
    "hat/models/losses/focal_loss.py",
    "hat/models/losses/giou_loss.py",
    "hat/models/losses/hinge_loss.py",
    "hat/models/losses/seg_loss.py",
    "hat/models/losses/smooth_l1_loss.py",
    "hat/models/losses/lnnorm_loss.py",
    "hat/models/losses/utils.py",
    "hat/models/losses/l1_loss.py",
    "hat/models/losses/mse_loss.py",
    "hat/models/losses/yolo_losses.py",
    "hat/models/necks/bifpn.py",
    "hat/models/necks/dw_unet.py",
    "hat/models/necks/fpn.py",
    "hat/models/necks/pafpn.py",
    "hat/models/necks/retinanet_fpn.py",
    "hat/models/necks/unet.py",
    "hat/models/necks/fast_scnn.py",
    "hat/models/necks/second_neck.py",
    "hat/models/necks/yolov3.py",
    "hat/models/necks/yolov3_group.py",
    "hat/models/structures/classifier.py",
    "hat/models/structures/detectors/retinanet.py",
    "hat/models/structures/detectors/fcos.py",
    "hat/models/structures/detectors/fcos3d.py",
    "hat/models/structures/detectors/pointpillars.py",
    "hat/models/structures/detectors/yolov3.py",
    "hat/models/structures/detectors/centerpoint.py",
    "hat/models/structures/segmentor.py",
    "hat/models/structures/encoder_decoder.py",
    "hat/models/structures/view_fusion.py",
    "hat/models/structures/detectors/detr3d.py",
    "hat/models/structures/disparity_pred/*",
    "hat/models/structures/lane_pred/ganet.py",
    "hat/models/structures/track_pred/motr.py",
    "hat/models/structures/opticalflow/pwcnet.py",
    "hat/models/structures/detectors/detr.py",
    "hat/models/structures/detectors/deform_detr.py",
    "hat/models/structures/lidar_multitask/lidar_multitask.py",
    "hat/models/structures/motion_forecasting.py",
    "hat/models/structures/keypoints/keypoint_model.py",
    "hat/models/task_modules/ganet/*",
    "hat/models/task_modules/motr/*",
    "hat/models/task_modules/pwcnet/*",
    "hat/models/task_modules/retinanet/*",
    "hat/models/task_modules/seg/*",
    "hat/models/task_modules/deeplab/*",
    "hat/models/task_modules/fcos3d/*",
    "hat/models/task_modules/deeplab/*",
    "hat/models/task_modules/fcn/*",
    "hat/models/task_modules/fcos/*",
    "hat/models/task_modules/yolo/*",
    "hat/models/task_modules/detr/*",
    "hat/models/task_modules/deform_detr/*",
    "hat/models/task_modules/view_fusion/*",
    "hat/models/task_modules/detr3d/*",
    "hat/models/task_modules/petr/*",
    "hat/models/task_modules/stereonet/*",
    "hat/models/task_modules/lidar/anchor_generator.py",
    "hat/models/task_modules/lidar/box_coders.py",
    "hat/models/task_modules/lidar/target_assigner.py",
    "hat/models/task_modules/lidar/pillar_encoder.py",
    "hat/models/task_modules/pointpillars/*",
    "hat/models/task_modules/centerpoint/*",
    "hat/models/task_modules/lidar_multitask/*",
    "hat/models/task_modules/carfusion_keypoints/*",
    "hat/models/task_modules/motion_forecasting/*",
    "hat/models/utils.py",
    "hat/models/weight_init.py",
    "hat/models/embeddings.py",
    "hat/profiler/memory_profiler.py",
    "hat/profiler/profilers.py",
    "hat/profiler/model_profiler.py",
    "hat/registry.py",
    "hat/utils/*",
    "hat/version.py",
    "hat/visualize/cls.py",
    "hat/visualize/det.py",
    "hat/visualize/lidar_det.py",
    "hat/visualize/seg.py",
    "hat/visualize/utils.py",
    "hat/visualize/disparity.py",
    "hat/visualize/cam3d.py",
    "hat/visualize/opticalflow.py",
    "hat/visualize/lane_lines.py",
    "hat/visualize/nuscenes.py",
    "hat/visualize/track.py",
    "hat/visualize/keypoints.py",
    "hat/visualize/argoverse.py",
    "tools/calops.py",
    "requirements",
    "dev/*",
    "setup.py",
    "Makefile",
    "README.md",
    "LICENSE",
    "requirements.txt",
]

copytodst = {
    "projects/toolchain/tools/datasets": "tools/datasets",
    "tools/deploy/compile_perf_hbir.py": "tools/hbir_compile_perf.py",
    "tools/deploy/export_hbir.py": "tools",
    "tools/deploy/export_onnx.py": "tools",
    "tools/deploy/hbir_model_check.py": "tools",
    "tools/deploy/hbir_validationV1.py": "tools/hbir_validation.py",
    "tools/deploy/hbir_inferV4.py": "tools/hbir_infer.py",
    "tools/analyze/compare_dump_data.py": "tools",
    "dev/api_generator": "tools/",
    "projects/toolchain/tools/dataset_converters/gen_mot_data.py": "tools/dataset_converters/",  # noqa
    "projects/toolchain/tools/dataset_converters/gen_carfusion_data.py": "tools/dataset_converters/",  # noqa
    "projects/toolchain/hbdk4/configs/bev": "configs/",
    "projects/toolchain/hbdk4/configs/classification": "configs/",
    "projects/toolchain/hbdk4/configs/detection": "configs/",
    "projects/toolchain/hbdk4/configs/segmentation": "configs/",
    "projects/toolchain/hbdk4/configs/track_pred": "configs/",
    "projects/toolchain/hbdk4/configs/disparity_pred": "configs/",
    "projects/toolchain/hbdk4/configs/lane_pred": "configs/",
    "projects/toolchain/hbdk4/configs/opticalflow_pred": "configs/",
    "projects/toolchain/hbdk4/configs/lidar_multi_task": "configs/",  # noqa
    "projects/toolchain/hbdk4/configs/keypoint/*": "configs/keypoint/",  # noqa
    "projects/toolchain/hbdk4/configs/traj_pred/*": "configs/traj_pred/",  # noqa
    "projects/toolchain/thirdparty/*": "hat/thirdparty/",
    "projects/toolchain/tools/align_bpu_validationV3.py": "tools/align_bpu_validation.py",  # noqa
    "projects/toolchain/tools/train.py": "tools/train.py",
    "projects/toolchain/tools/predict.py": "tools/predict.py",
    "projects/toolchain/tools/create_data.py": "tools/create_data.py",
    "projects/toolchain/tools/gen_camera_param_nusc.py": "tools/gen_camera_param_nusc.py",  # noqa
    "projects/toolchain/tools/homography_generator.py": "tools/homography_generator.py",  # noqa
    "projects/toolchain/tools/reference_points_generator.py": "tools/reference_points_generator.py",  # noqa
    "projects/toolchain/requirements/*": "requirements",
    "projects/toolchain/examples/": "examples",
    "projects/toolchain/hat/version.py": "hat/version.py",
    "projects/toolchain/setup.py": "setup.py",
    "projects/toolchain/hat/core/data_struct/base_struct.py": "hat/core/data_struct/base_struct.py",  # noqa
    "projects/toolchain/tests/": "tests",
}

skip_file_list = [
    "projects/toolchain/configs/bernoulli2",
    "hat/utils/trace.py",
    "hat/models/task_modules/fcos/converter.py",
    "hat/core/data_struct/app_struct.py",
]
