import logging
import os
from typing import Callable, List

import torch

from hat.callbacks.callbacks import CallbackMixin
from hat.registry import OBJECT_REGISTRY
from hat.utils.apply_func import _as_list
from hat.utils.distributed import get_dist_info, rank_zero_only
from hat.visualize.generate_video import GenerateVideo

__all__ = ["ANCSaveVisualize"]

logger = logging.getLogger(__name__)


@OBJECT_REGISTRY.register
class ANCSaveVisualize(CallbackMixin):
    """
    SaveVisualize callback is used for visualize results on specific tasks.

    Args:
        task_list: The list of tasks' name.
        visualize_list: The list of tasks' visualize function.
        video: Whether to generate video.
        basetask_list: The list of upper level tasks' name.
        save_dir: The save directory of images.
    """

    def __init__(
        self,
        task_list: List[str],
        visualize_list: List[Callable],
        basetask_list: List[str] = None,
        video: GenerateVideo = None,
        save_dir: str = "./",
    ):
        super(ANCSaveVisualize, self).__init__()
        self.task_list = task_list
        self.vis_list = visualize_list
        self.basetask_list = basetask_list if basetask_list else task_list
        self.video = video
        self.save_dir = save_dir
        self._task2vis = None
        self._basetask2vis = None
        self._basetask2task = None
        self.video_list = set()

    @property
    def task2vis(self):
        if not self._task2vis:
            self._task2vis = {
                task: vis_class
                for vis_class, task in zip(self.vis_list, self.task_list)
            }
        return self._task2vis

    @property
    def basetask2vis(self):
        if not self._basetask2vis:
            task2basetask = {
                task: basetask
                for basetask, task in zip(self.basetask_list, self.task_list)
            }
            self._basetask2task = {
                basetask: [] for basetask in self.basetask_list
            }
            for task, basetask in task2basetask.items():
                self._basetask2task[basetask].append(task)
            self._basetask2vis = {
                k: self.task2vis[v[0]] for k, v in self._basetask2task.items()
            }
        return self._basetask2vis

    def multitask_visualize(
        self, batch, model_outs, visualize, save_name, tasks
    ):
        for vis in _as_list(visualize):
            range_mode = getattr(vis, "range_mode", "")
            self.video_list.add(save_name + "_" + range_mode)
            save_path = os.path.join(
                self.save_dir, save_name + "_" + range_mode
            )
            os.makedirs(save_path, exist_ok=True)
            vis(batch, model_outs, tasks, save_path)

    def on_batch_end(self, batch, model_outs, **kwargs):
        if isinstance(batch, tuple):
            # this result is generated by multitask dataloader
            # each task has a result and format as (task_name, result)
            task = batch[1]
            visualize = self.task2vis[task]
            self.multitask_visualize(batch, model_outs, visualize, task, task)

        else:
            # this result is generated by common dataloader
            # all tasks ouput only one result
            for basetask, visualize in self.basetask2vis.items():
                tasks = self._basetask2task[basetask]
                self.multitask_visualize(
                    batch, model_outs, visualize, basetask, tasks
                )

        if get_dist_info()[1] > 1:
            torch.distributed.barrier()

    @rank_zero_only
    def on_epoch_end(self, **kwargs):
        if self.video:
            for task in self.video_list:
                self.video(
                    f"{task}.mp4",
                    os.path.join(self.save_dir, task),
                )
                self.video.size = None
